name: Build, Push and Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin <ecr-repository-url>

      - name: Build Docker image
        run: docker build -t <ecr-repository-url>/myapp:${{ github.sha }} .

      - name: Push Docker image to ECR
        run: docker push <ecr-repository-url>/myapp:${{ github.sha }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up AWS IAM Authenticator
        uses: aws-actions/aws-iam-authenticator@v1

      - name: Configure AWS EKS
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name <your-cluster-name>

      - name: Deploy to EKS
        run: |
          kubectl apply -f rkumar-namespace.yaml
          kubectl apply -f k8s-deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/myapp-deployment
